Database:
  mysql: false
  host: ''
  port: 3306
  database: ''
  user: ''
  password: ''

Config:
  permissão: 'preps.use'
  cooldown-tempo: 60 #MINUTOS

Mensagens:
  sem-permissão: '&cVocê não possui permissão para utilizar este comando.'
  comando-params: '&cUtilize /rep <+/-/ver/top> <jogador>.'
  jogador-não-encontrado: '&cEste jogador não está cadastrado no banco de dados.'
  ponto-positivo-enviado: '&aPonto positivo enviado ao jogador %jogador%.'
  ponto-negativo-enviado: '&cPonto negativo enviado ao jogador %jogador%.'
  cooldown-msg: '&cVocê precisa aguardar %tempo% para enviar outro ponto.'
  ver-pontos:
    - ''
    - ' &6&lPONTOS DE %jogador%'
    - ''
    - '  &b* &fPositivos: &a%pontos-positivos%'
    - '  &b* &fNegativos: &c%pontos-negativos%'
    - ''
  msg-top:
    - ''
    - ' &b&lTOP REPUTAÇÃO'
    - ''
    - ' &7* Você está visualizando os TOP 10 jogadores'
    - ' &7* com maior reputação &8positiva&7.'
    - ''
    - '%top10%'
    - ''

Top-config:
  msg: ' &7 %rank%º » &6%jogador%: &b%pontos-positivos%'